version: '3.9'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --timeout 120 --workers 2 design_website.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
