# Generated by Django 5.1.5 on 2025-01-27 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cover_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projects/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "jpg", "png", "pdf"]
                    )
                ],
            ),
        ),
    ]
