# Generated by Django 5.1.5 on 2025-01-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_project_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("RESIDENTIAL", "RESIDENTIAL"), ("COMMERCIAL", "COMMERCIAL")],
                default="COMMERCIAL",
                max_length=20,
            ),
        ),
    ]
