# Generated by Django 5.1.5 on 2025-02-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_contactuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="homepage_images/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[("banner", "Banner"), ("gallery", "Gallery")],
                        default="banner",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
