# Generated by Django 5.1.5 on 2025-02-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_homepageimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageImage',
        ),
    ]
