# Generated by Django 5.1.5 on 2025-07-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_contactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="address",
            field=models.CharField(
                default="Lalitpur, Nepal", help_text="Current Address", max_length=200
            ),
            preserve_default=False,
        ),
    ]
