# Generated by Django 5.1.5 on 2025-07-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_homepageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
